### ISSUE TITLE
It doesn't work in my case

### ISSUE THREAD

**Issue by sanmonmah** [blazor-demo/blazor-demo.github.io#2]
@SteveSandersonMS  I forked this repository, configured a project GitHub page and changed the segmentCounter to one.
the website [here is adress](https://sanmonmah.github.io/blazor-demo.github.io/) hangs on loading... and don't run the app like in your repository. 
am I missing any thing to get it running.

Thank you in advanced.

**Comment by sanmonmah** [comment]
@SteveSandersonMS  a detailed description how to reproduce your repository will be here helpful.

**Comment by SteveSandersonMS** [comment]
You haven't updated all the URLs in your site to match the location you're deploying to. I'm afraid I don't have step-by-step instructions so you'll need to investigate.
